services:
  mysql:
    image: mysql:8.4
    container_name: mysql_tzt
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: teatar_zatebe
      MYSQL_USER: tzt
      MYSQL_PASSWORD: tztpass
      TZ: Europe/Skopje
    ports:
      - "3306:3306"        # host:container (standard MySQL port)
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # auto-runs .sql on first start

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pma_tzt
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql

  php:
    image: php:8.2-apache
    container_name: php_tzt
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: teatar_zatebe
      DB_USER: tzt
      DB_PASS: tztpass
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "apt-get update && apt-get install -y libzip-dev zip unzip && 
             docker-php-ext-install pdo pdo_mysql zip && 
             apache2-foreground"

volumes:
  db_data:
